#ifndef QCEPDATAOBJECTPROPERTIESMODELPTR_H
#define QCEPDATAOBJECTPROPERTIESMODELPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QcepDataObjectPropertiesModel)

#endif // QCEPDATAOBJECTPROPERTIESMODELPTR_H
