#ifndef QCEPOUTPUTFILEFORMATTERSETTINGSPTR_H
#define QCEPOUTPUTFILEFORMATTERSETTINGSPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QcepOutputFileFormatterSettings)

#endif // QCEPOUTPUTFILEFORMATTERSETTINGSPTR_H
