#ifndef QCEPIMAGEQUEUEPTR_H
#define QCEPIMAGEQUEUEPTR_H

#include "qcepsharedpointer.h"

QCEP_SHAREDPOINTER(QcepImageBaseQueue)
QCEP_SHAREDPOINTER(QcepUInt16ImageQueue)
QCEP_SHAREDPOINTER(QcepInt16ImageQueue)
QCEP_SHAREDPOINTER(QcepUInt32ImageQueue)
QCEP_SHAREDPOINTER(QcepInt32ImageQueue)
QCEP_SHAREDPOINTER(QcepDoubleImageQueue)
QCEP_SHAREDPOINTER(QcepFloatImageQueue)
QCEP_SHAREDPOINTER(QcepMaskQueue)

#endif // QCEPIMAGEQUEUEPTR_H
